const canvas = document.getElementById('game-canvas');
const ctx = canvas.getContext('2d');
const TAU = Math.PI * 2;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const rand = (min, max) => Math.random() * (max - min) + min;
const choose = array => array[Math.floor(Math.random() * array.length)];

const SHIPS = [
  { id: 'interceptor', name: 'Interceptor', icon: '◈', color: '#5ce9d6', weapon: 'pulse', desc: 'Rapid fire / nimble frame', speed: 245, maxHp: 82, pickup: 78 },
  { id: 'bulwark', name: 'Bulwark', icon: '⬟', color: '#ff9b5b', weapon: 'flak', desc: 'Armored / close-range burst', speed: 175, maxHp: 138, pickup: 62 },
  { id: 'wraith', name: 'Wraith', icon: '◇', color: '#a89aff', weapon: 'drone', desc: 'Ghost-speed / seeking swarm', speed: 215, maxHp: 88, pickup: 108 },
  { id: 'vanguard', name: 'Vanguard', icon: '✦', color: '#c5f36b', weapon: 'orbit', desc: 'Heavy / orbiting blades', speed: 190, maxHp: 122, pickup: 72 },
  { id: 'demolitionist', name: 'Demolitionist', icon: '⊛', color: '#f4d35e', weapon: 'mine', desc: 'Trap-setting / area denial', speed: 170, maxHp: 108, pickup: 74 },
  { id: 'lancer', name: 'Lancer', icon: '╋', color: '#79c7ff', weapon: 'beam', desc: 'Long-range / piercing beam', speed: 205, maxHp: 94, pickup: 82 },
  { id: 'striker', name: 'Striker', icon: '▲', color: '#ff799c', weapon: 'missile', desc: 'Heavy ordnance / splash damage', speed: 165, maxHp: 118, pickup: 68 },
  { id: 'conduit', name: 'Conduit', icon: 'ϟ', color: '#f2ee9f', weapon: 'lightning', desc: 'Chain damage / crowd control', speed: 200, maxHp: 96, pickup: 90 }
];

const WEAPONS = {
  pulse: { name: 'Pulse Cannon', icon: '↯', color: '#5ce9d6', max: 6, tiers: ['+18 damage', '+25% fire rate', '+1 pierce', '+1 projectile', 'shots chain once', 'Singularity Beam'], evolution: 'singularity', base: { damage: 17, cooldown: .35, speed: 620, count: 1, pierce: 0 } },
  flak: { name: 'Flak Spread', icon: '✹', color: '#ff9b5b', max: 6, tiers: ['+22 damage', '+2 pellets', '+30% spread range', '+1 pierce', 'pellets explode', 'Starbreaker Flak'], evolution: 'starbreaker', base: { damage: 13, cooldown: .72, speed: 420, count: 5, pierce: 0 } },
  drone: { name: 'Drone Swarm', icon: '⌁', color: '#a89aff', max: 6, tiers: ['+1 drone', '+20% drone speed', '+18 damage', '+1 drone', 'drones split on hit', 'Wraith Armada'], evolution: 'armada', base: { damage: 22, cooldown: 1.25, speed: 260, count: 2, pierce: 0 } },
  orbit: { name: 'Blade Ring', icon: '✧', color: '#c5f36b', max: 6, tiers: ['+1 blade', '+35% orbit speed', '+20 damage', '+1 blade', '+1 blade and sparks', 'Halo of Ruin'], evolution: 'halo', base: { damage: 42, cooldown: .22, speed: 2.8, count: 3, pierce: 99 } },
  mine: { name: 'Mine Layer', icon: '⊛', color: '#f4d35e', max: 6, tiers: ['+25 damage', '+1 mine', '+20% blast radius', 'mines seek targets', '+1 mine', 'Gravimetric Bloom'], evolution: 'bloom', base: { damage: 52, cooldown: 2.5, speed: 0, count: 1, pierce: 99 } },
  beam: { name: 'Beam Lance', icon: '╋', color: '#79c7ff', max: 6, tiers: ['+20 damage', '+25% beam length', '-20% cooldown', '+1 beam angle', 'beam burns', 'Event Horizon'], evolution: 'horizon', base: { damage: 30, cooldown: 1.5, speed: 0, count: 1, pierce: 99 } },
  missile: { name: 'Missile Bay', icon: '▲', color: '#ff799c', max: 6, tiers: ['+45 damage', '+1 missile', '+35% blast radius', 'missiles accelerate', '+1 missile', 'Nova Salvo'], evolution: 'nova', base: { damage: 96, cooldown: 2.15, speed: 290, count: 1, pierce: 0 } },
  lightning: { name: 'Chain Lightning', icon: 'ϟ', color: '#f2ee9f', max: 6, tiers: ['+1 bounce', '+18 damage', '+1 bounce', '-20% cooldown', 'chain arcs widen', 'Storm Circuit'], evolution: 'storm', base: { damage: 35, cooldown: 1.35, speed: 0, count: 1, pierce: 99 } }
};
const POWERUPS = {
  engine: { name: 'Ion Engine', icon: '»', color: '#5ce9d6', max: 4, tiers: ['+12% speed', '+12% speed', '+18% speed', 'afterburner trail'], evolution: 'Nova Thrusters', evolutionEffect: '+35% speed and afterburner trail', stat: 'speed' },
  plating: { name: 'Reactive Plating', icon: '⬢', color: '#ff647c', max: 4, tiers: ['+20 max hull', '+15% damage reduction', '+30 max hull', 'hull repairs slowly'], evolution: 'Aegis Carapace', evolutionEffect: '+50 max hull and +20% damage reduction', stat: 'armor' },
  magnet: { name: 'Shard Magnet', icon: '⊙', color: '#a89aff', max: 4, tiers: ['+45 pickup radius', '+35 pickup radius', '+25% shard value', 'auto-collect pulse'], evolution: 'Event Magnet', evolutionEffect: '+100 pickup radius and +75% shard value', stat: 'pickup' },
  reactor: { name: 'Hot Reactor', icon: '♨', color: '#ff9b5b', max: 4, tiers: ['+10% fire rate', '+10% fire rate', '+15% fire rate', 'overdrive at low hull'], evolution: 'Overdrive Core', evolutionEffect: '+45% fire rate', stat: 'cooldown' },
  shield: { name: 'Void Shield', icon: '◉', color: '#79c7ff', max: 4, tiers: ['+1 shield charge', 'shield recharges', '+1 shield charge', 'shield nova'], evolution: 'Aegis Field', evolutionEffect: '+2 shield charges and faster recharge', stat: 'shield' },
  luck: { name: 'Experience Core', icon: '✣', color: '#c5f36b', max: 4, tiers: ['+15% experience earned', '+15% experience earned', '+25% experience earned', 'experience pickup pulse'], evolution: 'Singularity Archive', evolutionEffect: '+100% experience earned', stat: 'xp' }
};

let selectedShip = SHIPS.find(ship => ship.id === localStorage.getItem('void-selected-ship')) || SHIPS[0];
let game = null;
let animationId = 0;
let lastTime = 0;
let audioContext = null;
const soundCooldowns = {};
const keys = new Set();
const pointer = { active: false, x: 0, y: 0 };

function getAudioSettings() { try { return { volume: Number(localStorage.getItem('void-volume') ?? 70), muted: localStorage.getItem('void-muted') === 'true' }; } catch { return { volume: 70, muted: false }; } }
let audioSettings = getAudioSettings();
function unlockAudio() { if (!audioContext) audioContext = new (window.AudioContext || window.webkitAudioContext)(); if (audioContext.state === 'suspended') audioContext.resume(); }
function playTone(frequency, duration = .08, type = 'sine', volume = .035, slide = 0) { if (!audioContext || audioSettings.muted || audioSettings.volume === 0) return; const now = audioContext.currentTime; const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, now); oscillator.frequency.exponentialRampToValueAtTime(Math.max(40, frequency + slide), now + duration); gain.gain.setValueAtTime(.001, now); gain.gain.exponentialRampToValueAtTime(volume * audioSettings.volume / 100, now + .008); gain.gain.exponentialRampToValueAtTime(.001, now + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(now); oscillator.stop(now + duration + .02); }
function playSound(name) { if (!audioContext) return; const now = performance.now(); if (soundCooldowns[name] && now - soundCooldowns[name] < 45) return; soundCooldowns[name] = now; const sounds = { pulse: [620, .055, 'square', .018, -100], flak: [180, .11, 'sawtooth', .035, -90], drone: [310, .12, 'sine', .018, 80], orbit: [115, .07, 'triangle', .018, 35], mine: [90, .16, 'sawtooth', .028, -50], beam: [840, .12, 'sawtooth', .018, -160], missile: [130, .13, 'sawtooth', .03, 180], lightning: [980, .16, 'square', .025, -360], hit: [210, .035, 'square', .012, -40], pickup: [720, .08, 'sine', .022, 280], damage: [95, .18, 'sawtooth', .04, -45], shield: [460, .16, 'sine', .03, 280], level: [520, .22, 'triangle', .035, 420], evolve: [260, .5, 'sawtooth', .04, 760], boss: [80, .7, 'sawtooth', .045, -25], victory: [660, .65, 'triangle', .04, 520] }; const sound = sounds[name]; if (sound) playTone(...sound); }

function renderShipSelect() {
  const el = document.getElementById('ship-select');
    el.innerHTML = SHIPS.map((ship, index) => `<button class="ship-card ${index === 0 ? 'selected' : ''}" data-ship="${ship.id}" style="--ship-color:${ship.color}"><span class="ship-symbol">${ship.icon}</span><strong>${ship.name}</strong><small>${WEAPONS[ship.weapon].name}</small></button>`).join('');
  el.querySelectorAll('.ship-card').forEach(card => card.addEventListener('click', () => {
    selectedShip = SHIPS.find(ship => ship.id === card.dataset.ship);
    localStorage.setItem('void-selected-ship', selectedShip.id);
    el.querySelectorAll('.ship-card').forEach(item => item.classList.toggle('selected', item === card));
    renderSelectedShip();
    document.getElementById('ship-select-modal').classList.add('hidden');
  }));
}
function renderSelectedShip() { const ship = selectedShip; document.getElementById('selected-ship-preview').innerHTML = `<span class="selected-ship-icon" style="color:${ship.color}">${ship.icon}</span><span><strong>${ship.name}</strong><small>${WEAPONS[ship.weapon].name}</small></span>`; }

function setupCanvas() {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  canvas.width = innerWidth * dpr; canvas.height = innerHeight * dpr;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
}
function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
function angleTo(a, b) { return Math.atan2(b.y - a.y, b.x - a.x); }
function isEnemyOnScreen(enemy) { return enemy.x >= 0 && enemy.x <= innerWidth && enemy.y >= 80 && enemy.y <= innerHeight; }
function nearestEnemy(maxDistance = Infinity) {
  let target = null; let nearest = maxDistance;
  for (const enemy of game.enemies) { if (!isEnemyOnScreen(enemy)) continue; const dist = distance(game.player, enemy); if (dist < nearest) { nearest = dist; target = enemy; } }
  return target;
}
function addParticle(x, y, color, amount = 4, force = 1) { for (let i = 0; i < amount; i++) game.particles.push({ x, y, vx: rand(-70, 70) * force, vy: rand(-70, 70) * force, life: rand(.25, .7), max: .7, size: rand(1, 3), color }); }
function addText(x, y, text, color) { game.floating.push({ x, y, text, color, life: 1 }); }
function getLeaderboard() { try { return JSON.parse(localStorage.getItem('void-survivors-top-five') || '[]'); } catch { return []; } }
function getLeaderboardScore() { return Math.round(game.wave * 1000 + game.kills * 10 + game.shards); }
function submitNamedScore(name) { const entry = { score: getLeaderboardScore(), wave: game.wave, kills: game.kills, ship: selectedShip.name, name: name || 'PILOT' }; const records = [...getLeaderboard(), entry].sort((a, b) => b.score - a.score).slice(0, 5); localStorage.setItem('void-survivors-top-five', JSON.stringify(records)); renderLeaderboard(); }
function submitScore() { if (!game || game.scoreSubmitted) return; const score = getLeaderboardScore(); const records = getLeaderboard(); if (records.length < 5 || score > records[records.length - 1].score) { game.scoreSubmitted = true; document.getElementById('pilot-name').value = ''; document.getElementById('name-modal').classList.remove('hidden'); document.getElementById('pilot-name').focus(); } else game.scoreSubmitted = true; }
function renderLeaderboard() { const records = getLeaderboard(); document.getElementById('leaderboard-list').innerHTML = records.length ? records.map((entry, index) => `<div class="leaderboard-row"><b class="leaderboard-rank">${String(index + 1).padStart(2, '0')}</b><span class="leaderboard-ship">${entry.name || 'PILOT'}<small>${entry.ship} · WAVE ${entry.wave} · ${entry.kills} KILLS</small></span><strong>${entry.score.toLocaleString()}</strong></div>`).join('') : '<div class="leaderboard-empty">No flight records yet.<br>Launch a run to set the first score.</div>'; }

function createRun() {
  unlockAudio();
    const ship = selectedShip;
  game = {
    running: true, paused: false, godMode: false, endless: false, victory: false, elapsed: 0, kills: 0, shards: 0, level: 1, xp: 0, nextXp: 32, spawnTimer: 0, enemyId: 0, wave: 1, waveSpawned: 0, waveMiniSpawned: 0, bossSpawned: false,
        player: { x: innerWidth / 2, y: innerHeight / 2, ...ship, hp: ship.maxHp, speed: ship.speed, fireRate: 1, damageReduction: 0, pickup: ship.pickup, xpMultiplier: 1, shield: 0, shieldMax: 0, shieldRecharge: 0, lastHit: -10, invuln: 0, facing: -Math.PI / 2, weapons: [{ id: ship.weapon, level: 1, evolution: false }], powerups: [] },
    enemies: [], projectiles: [], enemyProjectiles: [], lightningArcs: [], explosions: [], shardsOnField: [], particles: [], floating: [], stars: Array.from({ length: 130 }, () => ({ x: rand(0, innerWidth), y: rand(0, innerHeight), z: rand(.2, 1.4) })),
    weaponTimers: {}, orbitAngle: 0
  };
  for (const weapon of game.player.weapons) game.weaponTimers[weapon.id] = .2;
  document.getElementById('start-screen').classList.remove('active');
  document.getElementById('game-screen').classList.add('active');
  document.getElementById('gameover-modal').classList.add('hidden');
  document.getElementById('victory-modal').classList.add('hidden');
  document.getElementById('god-mode-toggle').checked = false;
  updateHud(); renderLoadout(); lastTime = performance.now(); cancelAnimationFrame(animationId); animationId = requestAnimationFrame(loop);
}

function loop(now) {
  if (!game || !game.running) return;
  const dt = Math.min((now - lastTime) / 1000, .035); lastTime = now;
  if (!game.paused && document.getElementById('level-modal').classList.contains('hidden')) update(dt);
  draw(); animationId = requestAnimationFrame(loop);
}
function update(dt) {
  game.elapsed += dt; game.spawnTimer -= dt;
  updatePlayer(dt); updateSpawning(dt); updateEnemies(dt); updateWeapons(dt); updateProjectiles(dt); updatePickups(dt); updateEffects(dt);
  if (game.player.hp <= 0) endRun();
  updateHud();
}
function updatePlayer(dt) {
  let dx = 0, dy = 0;
  if (keys.has('a') || keys.has('arrowleft')) dx--; if (keys.has('d') || keys.has('arrowright')) dx++; if (keys.has('w') || keys.has('arrowup')) dy--; if (keys.has('s') || keys.has('arrowdown')) dy++;
  if (pointer.active) {
    const px = pointer.x - game.player.x;
    const py = pointer.y - game.player.y;
    const len = Math.hypot(px, py);
    if (len > 12) { dx = px / len; dy = py / len; }
  }
  const len = Math.hypot(dx, dy) || 1;
  if (dx !== 0 || dy !== 0) game.player.facing = Math.atan2(dy, dx);
  game.player.x = clamp(game.player.x + dx / len * game.player.speed * dt, 30, innerWidth - 30);
  game.player.y = clamp(game.player.y + dy / len * game.player.speed * dt, 80, innerHeight - 30);
  if (game.player.invuln > 0) game.player.invuln -= dt;
  if (game.player.shieldRecharge > 0) game.player.shieldRecharge -= dt;
  if (game.player.shieldRecharge <= 0 && game.player.shield < game.player.shieldMax) { game.player.shield++; game.player.shieldRecharge = 8; addText(game.player.x, game.player.y - 34, 'SHIELD RECHARGED', '#79c7ff'); addParticle(game.player.x, game.player.y, '#79c7ff', 18, 1.3); }
  if (game.player.armor >= 4 && game.player.hp < game.player.maxHp) game.player.hp = Math.min(game.player.maxHp, game.player.hp + dt * .7);
}
function updateSpawning(dt) {
  const wave = Math.floor(game.elapsed / 30) + 1;
  if (wave !== game.wave) { game.wave = wave; game.waveSpawned = 0; game.waveMiniSpawned = 0; game.bossSpawned = false; game.spawnTimer = 0; if (wave % 25 === 0) game.enemies.length = 0; }
  if (wave > 100 && !game.endless) { if (game.enemies.length === 0) showVictory(); return; }
  if (wave % 25 === 0) { if (!game.bossSpawned) { spawnEnemy('boss'); game.bossSpawned = true; } return; }
  const basicTarget = 20 + (wave - 1) * 5;
  const miniTarget = wave >= 5 ? 1 + Math.floor((wave - 5) / 5) : 0;
  const interval = Math.max(.16, 30 / basicTarget);
  if (game.spawnTimer <= 0 && game.waveSpawned < basicTarget) { spawnEnemy('basic'); game.waveSpawned++; game.spawnTimer = interval; }
  if (game.waveSpawned >= Math.floor(basicTarget * .35) && game.waveMiniSpawned < miniTarget && game.enemies.filter(enemy => enemy.mini).length < miniTarget) { spawnEnemy('mini'); game.waveMiniSpawned++; }
}
function spawnEnemy(type = 'basic') {
  const elite = type === 'mini'; const boss = type === 'boss';
  if (boss && game.wave < 25) return;
  if (boss) playSound('boss');
  const side = Math.floor(Math.random() * 4); const pad = 60; let x, y;
  if (side === 0) { x = rand(-pad, innerWidth + pad); y = -pad; } else if (side === 1) { x = innerWidth + pad; y = rand(-pad, innerHeight + pad); } else if (side === 2) { x = rand(-pad, innerWidth + pad); y = innerHeight + pad; } else { x = -pad; y = rand(-pad, innerHeight + pad); }
  const wave = game.wave; const basicHp = 24 + (wave - 1) * 9; const hp = boss ? 12000 + wave * 700 : elite ? 650 + wave * 45 : rand(basicHp * .85, basicHp * 1.15);
  game.enemies.push({ id: ++game.enemyId, x, y, hp, maxHp: hp, speed: boss ? 25 : elite ? 31 : rand(46, 78), radius: boss ? 48 : elite ? 28 : rand(11, 17), elite, mini: elite, boss, color: boss ? '#a89aff' : elite ? '#ff647c' : choose(['#df5873', '#e96e58', '#d45e9f']), hitFlash: 0, shoot: boss ? 1.2 : rand(1, 3), orbit: rand(0, TAU) });
}
function updateEnemies(dt) {
  for (let index = game.enemies.length - 1; index >= 0; index--) {
    const enemy = game.enemies[index]; const a = angleTo(enemy, game.player); const moveAngle = enemy.boss ? a + Math.sin(game.elapsed * 1.5 + enemy.orbit) * .55 : a; enemy.x += Math.cos(moveAngle) * enemy.speed * dt; enemy.y += Math.sin(moveAngle) * enemy.speed * dt; enemy.hitFlash -= dt; enemy.shoot -= dt;
    if (enemy.shoot <= 0 && (enemy.elite || enemy.boss)) { if (enemy.boss) { for (let shot = 0; shot < 10; shot++) { const spread = shot * TAU / 10 + game.elapsed * .35; game.enemyProjectiles.push({ x: enemy.x, y: enemy.y, vx: Math.cos(spread) * 125, vy: Math.sin(spread) * 125, life: 5, bossShot: true }); } game.enemyProjectiles.push({ x: enemy.x, y: enemy.y, vx: Math.cos(a) * 210, vy: Math.sin(a) * 210, life: 5, bossShot: true }); enemy.shoot = 3.5; } else { game.enemyProjectiles.push({ x: enemy.x, y: enemy.y, vx: Math.cos(a) * 115, vy: Math.sin(a) * 115, life: 4 }); enemy.shoot = 2.5; } }
    if (distance(enemy, game.player) < enemy.radius + 14 && game.player.invuln <= 0) { takeDamage(enemy.boss ? 35 : enemy.elite ? 18 : 8); enemy.x -= Math.cos(a) * 24; enemy.y -= Math.sin(a) * 24; }
  }
  for (let i = game.enemyProjectiles.length - 1; i >= 0; i--) { const shot = game.enemyProjectiles[i]; shot.x += shot.vx * dt; shot.y += shot.vy * dt; shot.life -= dt; if (shot.life <= 0) game.enemyProjectiles.splice(i, 1); else if (Math.hypot(shot.x - game.player.x, shot.y - game.player.y) < 13 && game.player.invuln <= 0) { takeDamage(12); game.enemyProjectiles.splice(i, 1); } }
}
function takeDamage(amount) { if (game.godMode) { addText(game.player.x, game.player.y - 24, 'GOD MODE', '#c5f36b'); return; } if (game.player.shield > 0) { game.player.shield--; game.player.shieldRecharge = 8; playSound('shield'); addText(game.player.x, game.player.y - 24, 'SHIELD', '#79c7ff'); addParticle(game.player.x, game.player.y, '#79c7ff', 14, 1.5); } else { game.player.hp -= Math.max(1, amount * (1 - game.player.damageReduction)); playSound('damage'); addText(game.player.x, game.player.y - 24, `-${Math.round(amount)}`, '#ff647c'); } game.player.invuln = .65; }

function weaponStats(weapon) { const data = WEAPONS[weapon.id], level = weapon.level; const s = { ...data.base }; s.damage *= 2 * (1 + (level - 1) * .2); s.count += weapon.id === 'orbit' ? (level >= 2 ? 1 : 0) + (level >= 4 ? 1 : 0) + (level >= 5 ? 1 : 0) : Math.floor((level - 1) / 3); s.pierce += Math.max(0, level - 3); s.cooldown *= Math.max(.55, 1 - (level - 1) * .06); if (weapon.id === 'orbit') s.speed *= level >= 2 ? 1.35 : 1; if (weapon.evolution) { s.damage *= 4; s.count += 3; s.pierce = 99; s.cooldown *= .5; } return s; }
function updateWeapons(dt) {
  const orbitWeapon = game.player.weapons.find(weapon => weapon.id === 'orbit');
    game.orbitAngle += dt * (orbitWeapon ? weaponStats(orbitWeapon).speed : 2.8);
  for (const weapon of game.player.weapons) {
    const stats = weaponStats(weapon); game.weaponTimers[weapon.id] = (game.weaponTimers[weapon.id] || 0) - dt * game.player.fireRate;
    if (weapon.id === 'orbit') continue;
    if (game.weaponTimers[weapon.id] <= 0) { fireWeapon(weapon, stats); game.weaponTimers[weapon.id] = stats.cooldown; }
  }
  if (orbitWeapon) { const orbit = orbitWeapon; const stats = weaponStats(orbit); const blades = stats.count + (orbit.evolution ? 3 : 0); const radius = orbit.evolution ? 92 : 78; for (let i = 0; i < blades; i++) { const angle = game.orbitAngle + i * TAU / blades; const x = game.player.x + Math.cos(angle) * radius; const y = game.player.y + Math.sin(angle) * radius; for (const enemy of game.enemies) if (Math.hypot(x - enemy.x, y - enemy.y) < enemy.radius + 10) { hitEnemy(enemy, stats.damage * dt * 2.4, '#c5f36b'); if (Math.random() < dt * 12) addParticle(x, y, '#c5f36b', 2); } } }
}
function fireWeapon(weapon, stats) {
  playSound(weapon.id);
  const target = nearestEnemy(); const baseAngle = target ? angleTo(game.player, target) : game.player.facing; const count = stats.count;
  if (weapon.id === 'beam') { for (let i = 0; i < count; i++) { const a = baseAngle + (i - (count - 1) / 2) * .16; game.projectiles.push({ type: 'beam', x: game.player.x, y: game.player.y, angle: a, life: weapon.evolution ? .3 : .15, damage: stats.damage, color: WEAPONS[weapon.id].color, evolved: weapon.evolution }); } return; }
  if (weapon.id === 'lightning') { let current = target, jumps = (weapon.evolution ? 7 : 3) + Math.floor((weapon.level - 1) / 2); const hit = []; while (current && !hit.includes(current) && hit.length <= jumps) { const source = hit.length ? hit[hit.length - 1] : game.player; hit.push(current); hitEnemy(current, stats.damage, '#f2ee9f'); game.lightningArcs.push({ from: { x: source.x, y: source.y }, to: { x: current.x, y: current.y }, life: weapon.evolution ? .34 : .18, max: weapon.evolution ? .34 : .18, evolved: weapon.evolution }); const next = game.enemies.filter(enemy => !hit.includes(enemy)).sort((a, b) => distance(current, a) - distance(current, b))[0]; if (!next || distance(current, next) > (weapon.evolution ? 230 : 170)) break; current = next; } return; }
  if (weapon.id === 'mine') { game.projectiles.push({ type: 'mine', x: game.player.x, y: game.player.y, life: 7, armed: 0.5, radius: 13, damage: stats.damage, color: WEAPONS[weapon.id].color }); return; }
  for (let i = 0; i < count; i++) { const spread = weapon.id === 'flak' ? (i - (count - 1) / 2) * .16 : (i - (count - 1) / 2) * .06; const a = baseAngle + spread; game.projectiles.push({ type: weapon.id, x: game.player.x, y: game.player.y, vx: Math.cos(a) * stats.speed, vy: Math.sin(a) * stats.speed, life: weapon.id === 'missile' ? 5 : 2.5, damage: stats.damage, pierce: stats.pierce, color: WEAPONS[weapon.id].color, homing: weapon.id === 'drone', evolved: weapon.evolution }); }
}
function updateProjectiles(dt) {
  for (let index = game.projectiles.length - 1; index >= 0; index--) {
    const shot = game.projectiles[index]; shot.life -= dt;
    if (shot.type === 'beam') { const beamRange = Math.hypot(innerWidth, innerHeight) * 2; for (const enemy of game.enemies) { const ex = enemy.x - shot.x, ey = enemy.y - shot.y; const along = ex * Math.cos(shot.angle) + ey * Math.sin(shot.angle); const side = Math.abs(-ex * Math.sin(shot.angle) + ey * Math.cos(shot.angle)); if (along > 0 && along < beamRange && side < enemy.radius + 8) hitEnemy(enemy, shot.damage * dt * 5, shot.color); } }
    else if (shot.type === 'mine') { if (shot.armed > 0) shot.armed -= dt; else { const nearby = game.enemies.find(enemy => distance(shot, enemy) < 70); if (nearby) { for (const enemy of game.enemies) if (distance(shot, enemy) < 82) hitEnemy(enemy, shot.damage, shot.color); addParticle(shot.x, shot.y, shot.color, 20, 2); shot.life = 0; } } }
    else { if (shot.homing) { const target = nearestEnemy(260); if (target) { const desired = angleTo(shot, target), current = Math.atan2(shot.vy, shot.vx), turn = Math.atan2(Math.sin(desired - current), Math.cos(desired - current)); const next = current + clamp(turn, -.08, .08); const speed = Math.hypot(shot.vx, shot.vy); shot.vx = Math.cos(next) * speed; shot.vy = Math.sin(next) * speed; } } shot.x += shot.vx * dt; shot.y += shot.vy * dt; const hit = game.enemies.find(enemy => distance(shot, enemy) < enemy.radius + 7); if (hit) { hitEnemy(hit, shot.damage, shot.color); if (shot.pierce > 0) shot.pierce--; else shot.life = 0; if (shot.type === 'missile') { for (const enemy of game.enemies) if (enemy !== hit && distance(shot, enemy) < 72) hitEnemy(enemy, shot.damage * .55, shot.color); game.explosions.push({ x: shot.x, y: shot.y, radius: 72, life: .32, max: .32, color: shot.color }); addParticle(shot.x, shot.y, shot.color, 20, 1.8); } } }
    if (shot.life <= 0 || shot.x < -80 || shot.x > innerWidth + 80 || shot.y < -80 || shot.y > innerHeight + 80) game.projectiles.splice(index, 1);
  }
}
function hitEnemy(enemy, damage, color) { if (!enemy || enemy.hp <= 0) return; enemy.hp -= damage; enemy.hitFlash = .08; playSound('hit'); if (Math.random() < .3) addParticle(enemy.x, enemy.y, color, 2); if (enemy.hp <= 0) killEnemy(enemy); }
function killEnemy(enemy) { const index = game.enemies.indexOf(enemy); if (index >= 0) game.enemies.splice(index, 1); game.kills++; playSound('hit'); const amount = enemy.boss ? 250 : enemy.elite ? 35 : 4; const visibleX = clamp(enemy.x, 24, innerWidth - 24); const visibleY = clamp(enemy.y, 82, innerHeight - 24); const offscreen = enemy.x < 24 || enemy.x > innerWidth - 24 || enemy.y < 82 || enemy.y > innerHeight - 24; game.shardsOnField.push({ x: visibleX, y: visibleY, value: amount, spin: rand(0, TAU), color: enemy.boss ? '#a89aff' : enemy.elite ? '#ff9b5b' : '#5ce9d6', incoming: offscreen }); addParticle(visibleX, visibleY, enemy.color, enemy.boss ? 70 : enemy.elite ? 30 : 8, enemy.boss ? 4 : enemy.elite ? 2 : 1); if (enemy.boss) addText(visibleX, visibleY - 50, '+250 XP', '#a89aff'); }
  function updatePickups(dt) { for (let index = game.shardsOnField.length - 1; index >= 0; index--) { const shard = game.shardsOnField[index]; shard.spin += dt * 4; const dist = distance(shard, game.player); if (shard.incoming) { const a = angleTo(shard, game.player); shard.x += Math.cos(a) * 190 * dt; shard.y += Math.sin(a) * 190 * dt; if (dist < 140) shard.incoming = false; } else if (dist < game.player.pickup) { const a = angleTo(shard, game.player); const pull = dist < 100 ? 310 : 140; shard.x += Math.cos(a) * pull * dt; shard.y += Math.sin(a) * pull * dt; } if (dist < 18) { game.xp += shard.value * game.player.xpMultiplier * (game.player.magnet >= 3 ? 1.25 : 1); game.shards += shard.value; playSound('pickup'); game.shardsOnField.splice(index, 1); addParticle(shard.x, shard.y, shard.color, 3); if (game.xp >= game.nextXp) levelUp(); } } }
function updateEffects(dt) { for (const particle of game.particles) { particle.x += particle.vx * dt; particle.y += particle.vy * dt; particle.life -= dt; particle.vx *= .96; particle.vy *= .96; } game.particles = game.particles.filter(particle => particle.life > 0); for (const text of game.floating) { text.y -= 24 * dt; text.life -= dt; } game.floating = game.floating.filter(text => text.life > 0); for (const arc of game.lightningArcs) arc.life -= dt; game.lightningArcs = game.lightningArcs.filter(arc => arc.life > 0); for (const explosion of game.explosions) explosion.life -= dt; game.explosions = game.explosions.filter(explosion => explosion.life > 0); }

function eligibleChoices() {
  const choices = [];
  for (const weapon of game.player.weapons) { const data = WEAPONS[weapon.id]; if (weapon.level < data.max) choices.push({ type: 'weapon-up', id: weapon.id }); else if (!weapon.evolution) choices.push({ type: 'evolution', id: weapon.id }); }
  for (const power of game.player.powerups) { const data = POWERUPS[power.id]; if (power.level < data.max) choices.push({ type: 'power-up', id: power.id }); else if (!power.evolution && data.evolution) choices.push({ type: 'power-evolution', id: power.id }); }
  if (game.player.weapons.length < 3) for (const id of Object.keys(WEAPONS)) if (!game.player.weapons.some(weapon => weapon.id === id)) choices.push({ type: 'new-weapon', id });
  if (game.player.powerups.length < 3) for (const id of Object.keys(POWERUPS)) if (!game.player.powerups.some(power => power.id === id)) choices.push({ type: 'new-power', id });
  return choices;
}
function levelUp() {
  while (game.xp >= game.nextXp) { game.xp -= game.nextXp; game.level++; game.nextXp = Math.round(game.nextXp * 1.22 + 8); playSound('level'); }
  const pool = eligibleChoices(); if (!pool.length) return;
  const options = []; while (options.length < Math.min(3, pool.length)) { const item = choose(pool); if (!options.some(option => option.type === item.type && option.id === item.id)) options.push(item); }
  while (options.length < 3) options.push(options[options.length % options.length]);
  document.getElementById('modal-level').textContent = game.level; const grid = document.getElementById('upgrade-grid'); grid.innerHTML = options.map((option, index) => upgradeMarkup(option, index)).join(''); grid.querySelectorAll('.upgrade-card').forEach((card, index) => card.addEventListener('click', () => applyChoice(options[index]))); document.getElementById('level-modal').classList.remove('hidden');
}
function upgradeMarkup(option, index) { let data, label, title, desc, tier, color; if (option.type === 'weapon-up' || option.type === 'new-weapon' || option.type === 'evolution') { data = WEAPONS[option.id]; const current = game.player.weapons.find(weapon => weapon.id === option.id); label = option.type === 'new-weapon' ? 'NEW WEAPON' : option.type === 'evolution' ? 'SUPER EVOLUTION' : 'WEAPON UPGRADE'; title = option.type === 'evolution' ? data.evolution.replace(/(^|_)(.)/g, (_, a, b) => b.toUpperCase()) : data.name; desc = option.type === 'new-weapon' ? `Starts with: ${data.tiers[0]}.` : option.type === 'evolution' ? `New behavior: ${data.tiers[data.max - 1]}.` : `Effect: ${data.tiers[current.level]}.`; tier = option.type === 'new-weapon' ? 'STARTS AT TIER 1' : option.type === 'evolution' ? 'FINAL FORM' : `TIER ${(current.level || 0) + 1} / ${data.max}`; color = data.color; } else { data = POWERUPS[option.id]; const current = game.player.powerups.find(power => power.id === option.id); const evolved = option.type === 'power-evolution'; label = option.type === 'new-power' ? 'NEW POWERUP' : evolved ? 'POWERUP EVOLUTION' : 'POWERUP UPGRADE'; title = evolved ? data.evolution : data.name; desc = option.type === 'new-power' ? `Passive effect: ${data.tiers[0]}.` : evolved ? `Evolution effect: ${data.evolutionEffect}.` : `Effect: ${data.tiers[current.level]}.`; tier = option.type === 'new-power' ? 'STARTS AT TIER 1' : evolved ? 'FINAL FORM' : `TIER ${(current.level || 0) + 1} / ${data.max}`; color = data.color; } return `<button class="upgrade-card" style="--choice-color:${color}"><span class="choice-type">${label}</span><span class="upgrade-icon">${data.icon}</span><strong>${title}</strong><p>${desc}</p><span class="tier"><b>${tier}</b></span></button>`; }
function applyChoice(option) { if (option.type === 'new-weapon') { game.player.weapons.push({ id: option.id, level: 1, evolution: false }); game.weaponTimers[option.id] = .2; } else if (option.type === 'weapon-up') game.player.weapons.find(weapon => weapon.id === option.id).level++; else if (option.type === 'evolution') { const weapon = game.player.weapons.find(item => item.id === option.id); weapon.evolution = true; addText(game.player.x, game.player.y - 44, 'EVOLUTION!', WEAPONS[option.id].color); addParticle(game.player.x, game.player.y, WEAPONS[option.id].color, 50, 3); } else if (option.type === 'new-power') game.player.powerups.push({ id: option.id, level: 1, evolution: false }); else if (option.type === 'power-evolution') { const power = game.player.powerups.find(item => item.id === option.id); power.evolution = true; addText(game.player.x, game.player.y - 44, 'POWERUP EVOLUTION!', POWERUPS[option.id].color); addParticle(game.player.x, game.player.y, POWERUPS[option.id].color, 35, 2); } else game.player.powerups.find(power => power.id === option.id).level++;
  playSound(option.type.includes('evolution') ? 'evolve' : 'level'); applyStats(); updateHud(); document.getElementById('level-modal').classList.add('hidden'); renderLoadout();
}
function applyStats() { const player = game.player; player.speed = selectedShip.speed; player.maxHp = selectedShip.maxHp; player.pickup = selectedShip.pickup; player.fireRate = 1; player.damageReduction = 0; player.magnet = 0; player.armor = 0; for (const power of player.powerups) { if (power.id === 'engine') player.speed += selectedShip.speed * .12 * power.level; if (power.id === 'plating') { player.maxHp += 20 * power.level; player.damageReduction = .08 * Math.floor((power.level + 1) / 2); player.armor = power.level; } if (power.id === 'magnet') { player.pickup += 45 * power.level; player.magnet = power.level; } if (power.id === 'reactor') player.fireRate += .1 * power.level; if (power.id === 'shield') player.shield = Math.max(player.shield, Math.ceil(power.level / 2)); } player.hp = Math.min(player.hp, player.maxHp); }
function applyStats() { const player = game.player; const previousShieldMax = player.shieldMax; player.speed = selectedShip.speed; player.maxHp = selectedShip.maxHp; player.pickup = selectedShip.pickup; player.fireRate = 1; player.damageReduction = 0; player.magnet = 0; player.armor = 0; player.xpMultiplier = 1; player.shieldMax = 0; for (const power of player.powerups) { const evolved = power.evolution; if (power.id === 'engine') player.speed += selectedShip.speed * (.12 * power.level + (evolved ? .35 : 0)); if (power.id === 'plating') { player.maxHp += 20 * power.level + (evolved ? 50 : 0); player.damageReduction = .08 * Math.floor((power.level + 1) / 2) + (evolved ? .2 : 0); player.armor = power.level; } if (power.id === 'magnet') { player.pickup += 45 * power.level + (evolved ? 100 : 0); player.magnet = power.level; } if (power.id === 'reactor') player.fireRate += .1 * power.level + (evolved ? .45 : 0); if (power.id === 'shield') player.shieldMax += Math.ceil(power.level / 2) + (evolved ? 2 : 0); if (power.id === 'luck') player.xpMultiplier += .15 * power.level + (evolved ? 1 : 0); } if (player.shieldMax === 0) player.shield = 0; else if (previousShieldMax === 0) player.shield = player.shieldMax; else if (player.shield > player.shieldMax) player.shield = player.shieldMax; player.hp = Math.min(player.hp, player.maxHp); }
function renderLoadout() { if (!game) return; const renderItems = (items, group) => items.map(item => { const data = group[item.id]; return `<div class="loadout-slot" style="--slot-color:${data.color}" title="${data.name}"><span class="slot-icon">${data.icon}</span><small>${item.evolution ? 'EVO' : `${data.name.split(' ')[0]} ${item.level}`}</small></div>`; }).join(''); document.getElementById('weapon-loadout').innerHTML = renderItems(game.player.weapons, WEAPONS); document.getElementById('powerup-loadout').innerHTML = renderItems(game.player.powerups, POWERUPS); }
function updateHud() { if (!game) return; const seconds = Math.floor(game.elapsed); document.getElementById('time-display').textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; document.getElementById('kill-display').textContent = game.kills; document.getElementById('level-display').textContent = `LVL ${game.level}`; document.getElementById('hull-bar').style.width = `${clamp(game.player.hp / game.player.maxHp * 100, 0, 100)}%`; document.getElementById('hull-value').textContent = `${Math.ceil(Math.max(0, game.player.hp))} / ${game.player.maxHp}`; document.getElementById('xp-bar').style.width = `${clamp(game.xp / game.nextXp * 100, 0, 100)}%`; document.getElementById('wave-display').textContent = `WAVE ${String(game.wave).padStart(2, '0')}`; }
function updateHud() { if (!game) return; const seconds = Math.floor(game.elapsed); document.getElementById('time-display').textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; document.getElementById('kill-display').textContent = game.kills; document.getElementById('level-display').textContent = `LVL ${game.level}`; document.getElementById('hull-bar').style.width = `${clamp(game.player.hp / game.player.maxHp * 100, 0, 100)}%`; document.getElementById('hull-value').textContent = `${Math.ceil(Math.max(0, game.player.hp))} / ${game.player.maxHp}`; document.getElementById('xp-bar').style.width = `${clamp(game.xp / game.nextXp * 100, 0, 100)}%`; const shieldStatus = document.getElementById('shield-status'); shieldStatus.classList.toggle('empty', game.player.shield <= 0); shieldStatus.classList.toggle('recharging', game.player.shield <= 0 && game.player.shieldMax > 0); document.getElementById('shield-value').textContent = game.player.shield > 0 ? `${game.player.shield} / ${game.player.shieldMax}` : game.player.shieldMax > 0 ? `RECHARGE ${Math.ceil(Math.max(0, game.player.shieldRecharge))}s` : 'NO SHIELD'; document.getElementById('wave-display').textContent = `WAVE ${String(game.wave).padStart(2, '0')}`; }

function draw() { ctx.clearRect(0, 0, innerWidth, innerHeight); if (!game) return; ctx.fillStyle = '#08111e'; ctx.fillRect(0, 0, innerWidth, innerHeight); drawSpace(); for (const shard of game.shardsOnField) drawShard(shard); for (const shot of game.enemyProjectiles) drawEnemyShot(shot); for (const enemy of game.enemies) drawEnemy(enemy); for (const shot of game.projectiles) drawProjectile(shot); drawLongBeams(); drawLightningArcs(); drawExplosions(); drawOrbit(); drawPlayer(); drawEffects(); }
function drawSpace() { ctx.save(); for (const star of game.stars) { ctx.fillStyle = `rgba(157, 203, 216, ${.15 + star.z * .26})`; ctx.fillRect((star.x - game.elapsed * star.z * 3) % innerWidth, star.y, star.z * 1.5, star.z * 1.5); } ctx.strokeStyle = 'rgba(105, 159, 178, .045)'; ctx.lineWidth = 1; const offset = (game.elapsed * 8) % 80; for (let x = -80 + offset; x < innerWidth + 80; x += 80) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x - innerHeight, innerHeight); ctx.stroke(); } ctx.restore(); }
function drawPlayer() { const player = game.player; if (player.shield > 0) { ctx.save(); ctx.strokeStyle = '#79c7ff'; ctx.shadowColor = '#79c7ff'; ctx.shadowBlur = 18; ctx.globalAlpha = .75 + Math.sin(game.elapsed * 5) * .15; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(player.x, player.y, 29 + Math.sin(game.elapsed * 3) * 2, 0, TAU); ctx.stroke(); ctx.restore(); } ctx.save(); ctx.translate(player.x, player.y); ctx.rotate(player.facing + Math.PI / 2); ctx.globalAlpha = player.invuln > 0 && Math.floor(player.invuln * 14) % 2 ? .35 : 1; ctx.shadowColor = selectedShip.color; ctx.shadowBlur = 20; ctx.fillStyle = '#d8e9ef'; ctx.beginPath(); ctx.moveTo(0, -20); ctx.lineTo(14, 15); ctx.lineTo(0, 10); ctx.lineTo(-14, 15); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = selectedShip.color; ctx.beginPath(); ctx.moveTo(0, -11); ctx.lineTo(5, 7); ctx.lineTo(-5, 7); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#ff9b5b'; ctx.fillRect(-3, 12, 6, 9); ctx.restore(); }
function drawOrbit() { const weapon = game.player.weapons.find(item => item.id === 'orbit'); if (!weapon) return; const stats = weaponStats(weapon), count = stats.count + (weapon.evolution ? 3 : 0), radius = weapon.evolution ? 74 : 60; for (let i = 0; i < count; i++) { const angle = game.orbitAngle + i * TAU / count, x = game.player.x + Math.cos(angle) * radius, y = game.player.y + Math.sin(angle) * radius; ctx.save(); ctx.translate(x, y); ctx.rotate(angle); ctx.fillStyle = weapon.evolution ? '#ffffff' : '#c5f36b'; ctx.shadowColor = weapon.evolution ? '#f2ee9f' : '#c5f36b'; ctx.shadowBlur = weapon.evolution ? 28 : 12; ctx.beginPath(); ctx.moveTo(0, weapon.evolution ? -18 : -12); ctx.lineTo(weapon.evolution ? 8 : 5, weapon.evolution ? 12 : 8); ctx.lineTo(0, weapon.evolution ? 18 : 12); ctx.lineTo(weapon.evolution ? -8 : -5, weapon.evolution ? 12 : 8); ctx.closePath(); ctx.fill(); ctx.restore(); } }
function drawOrbit() { const weapon = game.player.weapons.find(item => item.id === 'orbit'); if (!weapon) return; const stats = weaponStats(weapon), count = stats.count + (weapon.evolution ? 3 : 0), radius = weapon.evolution ? 92 : 78; for (let i = 0; i < count; i++) { const angle = game.orbitAngle + i * TAU / count, x = game.player.x + Math.cos(angle) * radius, y = game.player.y + Math.sin(angle) * radius; ctx.save(); ctx.translate(x, y); ctx.rotate(angle); ctx.fillStyle = weapon.evolution ? '#ffffff' : '#c5f36b'; ctx.shadowColor = weapon.evolution ? '#f2ee9f' : '#c5f36b'; ctx.shadowBlur = weapon.evolution ? 28 : 12; ctx.beginPath(); ctx.moveTo(0, weapon.evolution ? -18 : -12); ctx.lineTo(weapon.evolution ? 8 : 5, weapon.evolution ? 12 : 8); ctx.lineTo(0, weapon.evolution ? 18 : 12); ctx.lineTo(weapon.evolution ? -8 : -5, weapon.evolution ? 12 : 8); ctx.closePath(); ctx.fill(); ctx.restore(); } }
function drawEnemy(enemy) { ctx.save(); ctx.translate(enemy.x, enemy.y); ctx.rotate(Math.atan2(game.player.y - enemy.y, game.player.x - enemy.x)); ctx.fillStyle = enemy.hitFlash > 0 ? '#fff' : enemy.color; ctx.shadowColor = enemy.color; ctx.shadowBlur = enemy.boss ? 32 : enemy.elite ? 18 : 6; ctx.beginPath(); if (enemy.boss) { ctx.moveTo(0, -enemy.radius); for (let point = 1; point < 8; point++) { const angle = -Math.PI / 2 + point * TAU / 8; ctx.lineTo(Math.cos(angle) * enemy.radius, Math.sin(angle) * enemy.radius); } } else { ctx.moveTo(enemy.radius, 0); ctx.lineTo(-enemy.radius * .7, enemy.radius * .75); ctx.lineTo(-enemy.radius * .45, 0); ctx.lineTo(-enemy.radius * .7, -enemy.radius * .75); } ctx.closePath(); ctx.fill(); if (enemy.boss) { ctx.strokeStyle = '#f2ee9f'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(0, 0, enemy.radius + 12 + Math.sin(game.elapsed * 3) * 3, 0, TAU); ctx.stroke(); ctx.fillStyle = '#f2ee9f'; ctx.beginPath(); ctx.arc(0, 0, 10, 0, TAU); ctx.fill(); } else if (enemy.elite) { ctx.strokeStyle = '#ffb46b'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, enemy.radius + 7, 0, TAU); ctx.stroke(); } ctx.restore(); if (enemy.boss || enemy.elite) { ctx.fillStyle = 'rgba(255,100,124,.35)'; ctx.fillRect(enemy.x - (enemy.boss ? 48 : 27), enemy.y - enemy.radius - 13, enemy.boss ? 96 : 54, 4); ctx.fillStyle = enemy.boss ? '#a89aff' : '#ff647c'; ctx.fillRect(enemy.x - (enemy.boss ? 48 : 27), enemy.y - enemy.radius - 13, (enemy.boss ? 96 : 54) * enemy.hp / enemy.maxHp, 4); } }
function drawProjectile(shot) { ctx.save(); ctx.translate(shot.x, shot.y); if (shot.type === 'beam') { ctx.restore(); ctx.save(); ctx.strokeStyle = shot.evolved ? '#f2ee9f' : shot.color; ctx.shadowColor = shot.evolved ? '#f2ee9f' : shot.color; ctx.shadowBlur = shot.evolved ? 30 : 14; ctx.lineWidth = shot.evolved ? 11 : 4; ctx.beginPath(); ctx.moveTo(shot.x, shot.y); ctx.lineTo(shot.x + Math.cos(shot.angle) * (shot.evolved ? 720 : 520), shot.y + Math.sin(shot.angle) * (shot.evolved ? 720 : 520)); ctx.stroke(); ctx.restore(); return; } if (shot.type === 'mine') { ctx.fillStyle = shot.evolved ? '#ffffff' : shot.color; ctx.shadowColor = shot.evolved ? '#f2ee9f' : shot.color; ctx.shadowBlur = shot.evolved ? 24 : 10; ctx.beginPath(); ctx.arc(0, 0, (shot.evolved ? 15 : 9) + Math.sin(game.elapsed * 8) * 2, 0, TAU); ctx.fill(); ctx.strokeStyle = '#08111e'; ctx.stroke(); ctx.restore(); return; } ctx.rotate(Math.atan2(shot.vy, shot.vx)); ctx.fillStyle = shot.color; ctx.shadowColor = shot.evolved ? '#f2ee9f' : shot.color; ctx.shadowBlur = shot.evolved ? 24 : shot.type === 'missile' ? 18 : 9; if (shot.type === 'missile') { ctx.fillStyle = shot.evolved ? '#ffffff' : '#ffd0d9'; ctx.beginPath(); ctx.moveTo(shot.evolved ? 18 : 13, 0); ctx.lineTo(-8, shot.evolved ? 9 : 6); ctx.lineTo(-5, 0); ctx.lineTo(-8, shot.evolved ? -9 : -6); ctx.closePath(); ctx.fill(); ctx.fillStyle = shot.color; ctx.fillRect(-13, -3, 8, 6); ctx.fillStyle = '#ff9b5b'; ctx.fillRect(-18, -2, shot.evolved ? 12 : 6, 4); } else if (shot.evolved) { ctx.fillStyle = '#ffffff'; ctx.beginPath(); ctx.arc(0, 0, 7, 0, TAU); ctx.fill(); ctx.fillStyle = shot.color; ctx.fillRect(-14, -3, 28, 6); } else ctx.fillRect(-8, -2, 16, 4); ctx.restore(); }
function drawEnemyShot(shot) { ctx.fillStyle = '#ff647c'; ctx.shadowColor = '#ff647c'; ctx.shadowBlur = 9; ctx.beginPath(); ctx.arc(shot.x, shot.y, 4, 0, TAU); ctx.fill(); }
function drawLightningArcs() { for (const arc of game.lightningArcs) { const progress = arc.life / arc.max; const dx = arc.to.x - arc.from.x, dy = arc.to.y - arc.from.y, length = Math.hypot(dx, dy); const nx = -dy / length, ny = dx / length; ctx.save(); ctx.globalAlpha = progress; ctx.strokeStyle = arc.evolved ? '#ffffff' : '#f2ee9f'; ctx.shadowColor = arc.evolved ? '#a89aff' : '#f2ee9f'; ctx.shadowBlur = arc.evolved ? 30 : 16; ctx.lineWidth = arc.evolved ? 8 : 4; ctx.beginPath(); ctx.moveTo(arc.from.x, arc.from.y); for (let step = 1; step < 5; step++) { const along = step / 5, offset = (Math.random() - .5) * (arc.evolved ? 30 : 18); ctx.lineTo(arc.from.x + dx * along + nx * offset, arc.from.y + dy * along + ny * offset); } ctx.lineTo(arc.to.x, arc.to.y); ctx.stroke(); ctx.restore(); } }
function drawLongBeams() { const range = Math.hypot(innerWidth, innerHeight) * 2; for (const shot of game.projectiles) { if (shot.type !== 'beam') continue; ctx.save(); ctx.globalAlpha = .42; ctx.strokeStyle = shot.evolved ? '#ffffff' : shot.color; ctx.shadowColor = shot.evolved ? '#f2ee9f' : shot.color; ctx.shadowBlur = shot.evolved ? 22 : 10; ctx.lineWidth = shot.evolved ? 5 : 2; ctx.beginPath(); ctx.moveTo(shot.x, shot.y); ctx.lineTo(shot.x + Math.cos(shot.angle) * range, shot.y + Math.sin(shot.angle) * range); ctx.stroke(); ctx.restore(); } }
function drawExplosions() { for (const explosion of game.explosions) { const progress = explosion.life / explosion.max; ctx.save(); ctx.globalAlpha = progress; ctx.strokeStyle = explosion.color; ctx.shadowColor = explosion.color; ctx.shadowBlur = 18; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(explosion.x, explosion.y, explosion.radius * (1 - progress * .35), 0, TAU); ctx.stroke(); ctx.restore(); } }
function drawShard(shard) { ctx.save(); ctx.translate(shard.x, shard.y); ctx.rotate(shard.spin); ctx.fillStyle = shard.color; ctx.shadowColor = shard.color; ctx.shadowBlur = 8; ctx.beginPath(); ctx.moveTo(0, -6); ctx.lineTo(4, 0); ctx.lineTo(0, 6); ctx.lineTo(-4, 0); ctx.closePath(); ctx.fill(); ctx.restore(); }
function drawEffects() { for (const particle of game.particles) { ctx.globalAlpha = particle.life / particle.max; ctx.fillStyle = particle.color; ctx.fillRect(particle.x, particle.y, particle.size, particle.size); } ctx.globalAlpha = 1; for (const text of game.floating) { ctx.globalAlpha = text.life; ctx.fillStyle = text.color; ctx.font = '700 12px Barlow Condensed'; ctx.fillText(text.text, text.x, text.y); } ctx.globalAlpha = 1; }
function endRun() { game.running = false; submitScore(); document.getElementById('result-time').textContent = document.getElementById('time-display').textContent; document.getElementById('result-kills').textContent = game.kills; document.getElementById('result-shards').textContent = game.shards; document.getElementById('gameover-modal').classList.remove('hidden'); }
function showVictory() { if (game.victory) return; submitScore(); game.victory = true; game.paused = true; document.getElementById('victory-time').textContent = document.getElementById('time-display').textContent; document.getElementById('victory-kills').textContent = game.kills; document.getElementById('victory-shards').textContent = game.shards; document.getElementById('victory-modal').classList.remove('hidden'); }
function finishRun() { game.running = false; game.paused = false; document.getElementById('victory-modal').classList.add('hidden'); document.getElementById('game-screen').classList.remove('active'); document.getElementById('start-screen').classList.add('active'); }
function continueEndless() { game.endless = true; game.victory = false; game.paused = false; document.getElementById('victory-modal').classList.add('hidden'); }
function togglePause() { if (!game || !game.running || !document.getElementById('level-modal').classList.contains('hidden')) return; game.paused = !game.paused; const pauseModal = document.getElementById('pause-modal'); pauseModal.classList.toggle('hidden', !game.paused); if (game.paused) document.getElementById('god-mode-toggle').checked = game.godMode; }

renderShipSelect(); renderSelectedShip(); setupCanvas(); addEventListener('resize', setupCanvas); addEventListener('keydown', event => { keys.add(event.key.toLowerCase()); if (event.key === 'Escape') togglePause(); }); addEventListener('keyup', event => keys.delete(event.key.toLowerCase()));
document.getElementById('launch-btn').addEventListener('click', createRun); document.getElementById('choose-ship-btn').addEventListener('click', () => document.getElementById('ship-select-modal').classList.remove('hidden')); document.getElementById('close-ship-select').addEventListener('click', () => document.getElementById('ship-select-modal').classList.add('hidden')); document.getElementById('settings-btn').addEventListener('click', () => { document.getElementById('volume-slider').value = audioSettings.volume; document.getElementById('volume-value').textContent = `${audioSettings.volume}%`; document.getElementById('mute-toggle').checked = audioSettings.muted; document.getElementById('settings-modal').classList.remove('hidden'); }); document.getElementById('close-settings').addEventListener('click', () => document.getElementById('settings-modal').classList.add('hidden')); document.getElementById('volume-slider').addEventListener('input', event => { audioSettings.volume = Number(event.target.value); localStorage.setItem('void-volume', audioSettings.volume); document.getElementById('volume-value').textContent = `${audioSettings.volume}%`; unlockAudio(); playSound('level'); }); document.getElementById('mute-toggle').addEventListener('change', event => { audioSettings.muted = event.target.checked; localStorage.setItem('void-muted', audioSettings.muted); }); document.getElementById('name-form').addEventListener('submit', event => { event.preventDefault(); submitNamedScore(document.getElementById('pilot-name').value.trim()); document.getElementById('name-modal').classList.add('hidden'); }); document.getElementById('leaderboard-btn').addEventListener('click', () => { renderLeaderboard(); document.getElementById('leaderboard-modal').classList.remove('hidden'); }); document.getElementById('close-leaderboard').addEventListener('click', () => document.getElementById('leaderboard-modal').classList.add('hidden')); document.getElementById('clear-leaderboard').addEventListener('click', () => { localStorage.removeItem('void-survivors-top-five'); renderLeaderboard(); }); document.getElementById('again-btn').addEventListener('click', createRun); document.getElementById('restart-btn').addEventListener('click', createRun); document.getElementById('finish-btn').addEventListener('click', finishRun); document.getElementById('endless-btn').addEventListener('click', continueEndless); document.getElementById('pause-btn').addEventListener('click', togglePause); document.getElementById('god-mode-toggle').addEventListener('change', event => { if (game) game.godMode = event.target.checked; }); document.getElementById('resume-btn').addEventListener('click', togglePause); document.getElementById('quit-btn').addEventListener('click', () => { game.running = false; document.getElementById('pause-modal').classList.add('hidden'); document.getElementById('game-screen').classList.remove('active'); document.getElementById('start-screen').classList.add('active'); });
function setPointer(event) { const rect = canvas.getBoundingClientRect(); pointer.x = event.clientX - rect.left; pointer.y = event.clientY - rect.top; }
canvas.addEventListener('pointerdown', event => { pointer.active = true; setPointer(event); canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointermove', event => { if (pointer.active) setPointer(event); }); canvas.addEventListener('pointerup', () => { pointer.active = false; }); canvas.addEventListener('pointercancel', () => { pointer.active = false; });
